import { database, baseUrl } from './firebase-config.js';
import { ref, onValue } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-database.js";

const jobsState = { jobs: [], search: '', status: 'all', category: 'all', country: 'all' };
function esc(v) { return String(v ?? '').replace(/[&<>"']/g, (m) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[m])); }
function parseDate(value) { const d = new Date(value || 0); return Number.isNaN(d.getTime()) ? 0 : d.getTime(); }
function jobStatusText(status) { const s = String(status || 'open').toLowerCase().replace(/_/g,' '); return s.charAt(0).toUpperCase() + s.slice(1); }
function normalizeJobs(node) { if (!node) return []; const list = Array.isArray(node) ? node : Object.entries(node).map(([id,item]) => ({ id, ...(item || {}) })); return list.map((job) => ({ id: job.id || job.key || job.jobId || '', title: job.title || job.jobTitle || 'Untitled Job', jobTitle: job.jobTitle || job.title || 'Untitled Job', category: job.category || job.jobCategory || 'Uncategorized', jobCategory: job.jobCategory || job.category || 'Uncategorized', country: job.country || '—', slots: Number(job.slots || job.openings || 1) || 1, salary: job.salary || job.pay || '', status: job.status || job.state || 'open', state: job.state || job.status || 'open', icon: job.icon || '🏭', description: job.description || '', highlights: Array.isArray(job.highlights) ? job.highlights : [], requirements: Array.isArray(job.requirements) ? job.requirements : [], deadline: job.deadline || '', featured: !!job.featured, createdAt: job.createdAt || '', updatedAt: job.updatedAt || '' })); }
function filterMatch(job) { const haystack = [job.title, job.jobTitle, job.category, job.jobCategory, job.country, job.description, job.salary, job.pay, job.status, job.state, ...(Array.isArray(job.highlights) ? job.highlights : []), ...(Array.isArray(job.requirements) ? job.requirements : [])].filter(Boolean).join(' ').toLowerCase(); const status = String(job.status || job.state || 'open').toLowerCase(); const category = String(job.category || job.jobCategory || '').toLowerCase(); const country = String(job.country || '').toLowerCase(); if (jobsState.search && !haystack.includes(jobsState.search)) return false; if (jobsState.status !== 'all' && status !== jobsState.status) return false; if (jobsState.category !== 'all' && category !== jobsState.category) return false; if (jobsState.country !== 'all' && country !== jobsState.country) return false; return true; }
function setStatus(container, hasData, hasError=false) { const statusEl = container?.querySelector('[data-jobs-status]'); if (statusEl) statusEl.textContent = hasError ? 'Unable to get data' : (hasData ? 'Data confirmed' : 'Getting data'); }
function emptyView(container, message) { const grid = container?.querySelector('[data-jobs-grid]'); if (grid) grid.innerHTML = `<div class="jobs-empty-state"><div class="jobs-empty-title">${esc(message)}</div><div class="jobs-empty-sub">Refresh after Firebase receives a job post.</div></div>`; }
function renderJobs() { const views = Array.from(document.querySelectorAll('[data-jobs-view]')); const filtered = jobsState.jobs.slice().sort((a,b) => parseDate(b.createdAt || b.updatedAt) - parseDate(a.createdAt || a.updatedAt)).filter(filterMatch); views.forEach((container) => { const grid = container.querySelector('[data-jobs-grid]'); const countEl = container.querySelector('[data-jobs-count]'); if (countEl) countEl.textContent = `(${filtered.length})`; setStatus(container, jobsState.jobs.length > 0, false); if (!grid) return; if (!filtered.length) { emptyView(container, jobsState.jobs.length ? 'No jobs match the current filters.' : 'Getting data from Firebase...'); return; } grid.innerHTML = filtered.map((job) => { const featured = job.featured || String(job.status).toLowerCase() === 'featured'; const status = String(job.status || job.state || 'open').toLowerCase(); const actionLabel = status === 'filled' ? 'Contact Us' : 'Apply Now'; const actionHref = status === 'filled' ? 'contact.html' : `${baseUrl}payment.html?job=${encodeURIComponent(job.title)}`; const chips = [job.category, job.country, `${job.slots} Slots`, job.salary || ''].filter(Boolean); return `<article class="job-card ${featured ? 'job-card-featured' : ''}"><div class="job-card-top"><div class="job-icon">${esc(job.icon)}</div><div class="job-badge">${esc(jobStatusText(status))}</div></div><h2 class="job-name">${esc(job.title)}</h2><p class="job-desc">${esc(job.description || 'No description was added yet.')}</p><div class="job-tags">${chips.map((chip) => `<span class="job-tag ${chip === job.salary ? 'highlight' : ''}">${esc(chip)}</span>`).join('')}</div><div class="job-footer"><span>${esc(job.country)} · ${esc(String(job.slots))} Slots</span><a class="apply-btn" href="${esc(actionHref)}">${esc(actionLabel)}</a></div></article>`; }).join(''); }); }
function refreshFilters() { jobsState.search = ''; jobsState.status = 'all'; jobsState.category = 'all'; jobsState.country = 'all'; document.querySelectorAll('[data-jobs-search]').forEach((el) => { if (el.value) jobsState.search = String(el.value).trim().toLowerCase(); }); document.querySelectorAll('[data-jobs-status]').forEach((el) => { if (el.value) jobsState.status = String(el.value).toLowerCase(); }); document.querySelectorAll('[data-jobs-category]').forEach((el) => { if (el.value) jobsState.category = String(el.value).trim().toLowerCase(); }); document.querySelectorAll('[data-jobs-country]').forEach((el) => { if (el.value) jobsState.country = String(el.value).trim().toLowerCase(); }); renderJobs(); }
function populateFilters() { const categories = [...new Set(jobsState.jobs.map((j) => String(j.category || j.jobCategory || '').trim()).filter(Boolean))].sort((a,b) => a.localeCompare(b)); const countries = [...new Set(jobsState.jobs.map((j) => String(j.country || '').trim()).filter(Boolean))].sort((a,b) => a.localeCompare(b)); document.querySelectorAll('[data-jobs-category]').forEach((select) => { const current = select.value || 'all'; select.innerHTML = `<option value="all">All Categories</option>` + categories.map((c) => `<option value="${esc(c.toLowerCase())}">${esc(c)}</option>`).join(''); select.value = current; }); document.querySelectorAll('[data-jobs-country]').forEach((select) => { const current = select.value || 'all'; select.innerHTML = `<option value="all">All Countries</option>` + countries.map((c) => `<option value="${esc(c.toLowerCase())}">${esc(c)}</option>`).join(''); select.value = current; }); }
function initJobsLive() { onValue(ref(database, 'jobs'), (snap) => { jobsState.jobs = normalizeJobs(snap.val()); populateFilters(); renderJobs(); }, (error) => { console.error(error); document.querySelectorAll('[data-jobs-view]').forEach((container) => { setStatus(container, false, true); emptyView(container, 'Unable to get data'); }); }); document.querySelectorAll('[data-jobs-search]').forEach((el) => el.addEventListener('input', refreshFilters)); document.querySelectorAll('[data-jobs-status], [data-jobs-category], [data-jobs-country]').forEach((el) => el.addEventListener('change', refreshFilters)); }
document.addEventListener('DOMContentLoaded', initJobsLive);
